### ISSUE TITLE
Add live refresh for customizer controls

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#104]
More details: https://make.wordpress.org/core/2016/02/16/selective-refresh-in-the-customizer/

**Comment by c0sm1n87** [comment]
multe optiuni se activeaza/dezactiveaza prin get_template_part .. deci refresh trebuie sa se faca. site title/description se intampla REAL TIME, probabil e usor de facut si pentru copyright area.. tu la ce te mai gandeai ?

**Comment by cristianraiber** [comment]
Color schemes si sa adaugam live refresh si pe widgetzi :) Ca acum dau refresh la toata pagina

**Comment by c0sm1n87** [comment]
color schemes nu cred ca e asa usor.. ca trebuie practic sa inlocuiesti assets/style.css

**Comment by cristianraiber** [comment]
@c0sm1n87 - am mutat milestone-ul. Am gasit recent o librarie gata codata pt. treaba asta :) 

https://github.com/NateWr/theme-painter
