### ISSUE TITLE
Improve w.org theme demo

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#109]
Trebuie sa adaugam demo data din widgetzii default ai WP-ului pe sidebar-ul de blog si pe sidebar-urile din footer.

**Comment by cristianraiber** [comment]
@c0sm1n87 - adauga si al 4 lea widget in footer aici :) Degeaba facem 4 cols daca nu avem 4 widgetzi :P

**Comment by c0sm1n87** [comment]
https://github.com/MachoThemes/newsmag-lite/blob/master/sidebar-footer.php#L51 ?

**Comment by cristianraiber** [comment]
@c0sm1n87 - sometimes, I'm smart; sometimes, I'm not.
