### ISSUE TITLE
Wordpress widgets - Recent posts

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#111]
- [x] Line height pe title ar trebui sa fie 20px sa il facem similar cu [one column]
- [ ] Imaginea ar trebui sa aiba o inaltime de 75px, as folopress thumbnail aici ca din ce vad incarca imaginea la dimensiunea ei intreaga
- [x] Titlul ar trebui sa aiba un margin top de 10px 

![image](https://cloud.githubusercontent.com/assets/113568/19171376/07eff0c4-8c25-11e6-8e87-982099a9bca9.png)

![image](https://cloud.githubusercontent.com/assets/113568/19171449/7f293074-8c25-11e6-9dcb-37e3d3a1e0aa.png)

**Comment by c0sm1n87** [comment]
mda, am uitat sa iau "size`u" asignat pentru widgetu asta :D

**Comment by cristianraiber** [comment]
@c0sm1n87 - margin-top-ul e de 7px, nu de 10px
@c0sm1n87 - cred ca ce incerca @ngabyn sa zica aici era faptul ca imaginea ar trebui luata sub forma `wp_get_attachment_image_src( get_post_thumbnail_id(), 'thumbnail' );`. Momentan, placeholdere-le au 68 x 68 (desi spatiu ar fi, ai alocat un col-md-3) iar pozele urcat prin media uploader ies la niste proportii dubioase :)

**Comment by c0sm1n87** [comment]
![1](https://cloud.githubusercontent.com/assets/10389279/19186892/18047d24-8c91-11e6-9904-d6a843066ad4.jpg)

**Comment by c0sm1n87** [comment]
da, acum vad in sectiunea de sus (ONE COLUMN) unde e postul mic - widthul imaginii e 65px, iar la recent e de 75px .. o sa fac separat 👍

**Comment by c0sm1n87** [comment]
te bucuri degeaba :)) nu mai fac separat. o sa ramana amandoua la 65px ( am discutat pe slack cu gabi )

**Comment by cristianraiber** [comment]
I hate you both ... equally!

**Comment by ngabyn** [comment]
It's okay, we hate you too!
