### ISSUE TITLE
Customizer: control excerpt length (range slider)

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#112]
As vrea sa pot controla lungimea excerpt-ului ca ce size are acum, by default imi ca strica layout-ul :)

**Comment by ngabyn** [comment]
Lungimea lui nu se seteaza by value ci se intinde cat containerul lui ceea ce ar trebui sa fie la un 10px  sau 20 px left right o sa ma uit...

**Comment by c0sm1n87** [comment]
f8af53388b56571dcc94d5099a734a333303ced5 am scris aiurea issue id

**Comment by cristianraiber** [comment]
@c0sm1n87 - change label from: "Number of words outputted by the excerpt?" to "Post excerpt length" si muta-l ca si control deasupra 

@ngabyn - scoatem descrierea aici? https://macho-themes.slack.com/files/cristian/F2LLF8Y1G/pasted_image_at_2016_10_07_15_18.png

**Comment by ngabyn** [comment]
nu vad nici o imagine man...repost one visible image
