### ISSUE TITLE
Breadcrumbs single or blog wide

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#113]
Se pare ca daca activam breadcrumbs pe single e valabil si pe index ... cred ca ar trebui sa fie la general @cristianraiber an opinion on where we move this ?

![image](https://cloud.githubusercontent.com/assets/113568/19174114/2de53e78-8c35-11e6-8ff0-d3b502b2a54b.png)

- [ ] Breadcrumbs on index applies to single setting (hai sa alegem functionarea)
- [ ] Afisarea indexului doar cu Home -->  nu imi pare foarte utila...  oare e ok ?

**Comment by cristianraiber** [comment]
@ngabyn - am putea sa o scoatem de pe blog index, si s-o lasam pe singular momenta (pages, posts, etc)
