### ISSUE TITLE
Improved naming on sidebars

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#115]
![image](https://cloud.githubusercontent.com/assets/113568/19174241/fcc0faac-8c35-11e6-867e-d9dab583e327.png)

**Homepage - Header area**
_This sidebar holds the header slider area. Full-width widgets only should be placed in here. Currently, Newsmag only support the slider widget as full-width._

**Homepage - Content area**
_The sidebar holds the entire homepage content, place "Newsmag - Homepage builder" widgets here._

@cristianraiber chiar nu vrei sa renuntam la : ? :P
@cristianraiber review my suggestions as test first please!

**Comment by ngabyn** [comment]
:))))) simple issue simple fix

**Comment by cristianraiber** [comment]
@c0sm1n87 - aici ai gresit. Ai pus content-ul de la "content sidebar" la "blog sidebar" ... ntz ntz ntz

**Comment by c0sm1n87** [comment]
i`m a simple man, i see sidebar, i change description

**Comment by c0sm1n87** [comment]
5c8a4cd6b22cf5fdaf518d3aa00b106eb78188de

**Comment by cristianraiber** [comment]
@c0sm1n87 - ok, mi-au scapat cateva (sry)

1. Blog sidebar description: _This is the blog sidebar. If you've set a posts page under Settings -> Reading, that's where your sidebar will be showing up. _
2. Footer 1-4 description: _This is your footer sidebar. By default, we've defined a maximum of 4 sidebars but if you want to use less make sure you change the settings in: Footer -> Footer columns._

**Comment by ngabyn** [comment]
Nu uita de sidebar title:

Homepage - Header area
Homepage - Content area
