### ISSUE TITLE
Homepage builder - Post banner x 8

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#116]
![image](https://cloud.githubusercontent.com/assets/113568/19174439/896c8bd2-8c37-11e6-9b76-5dcd46c5566b.png)

- [x] adaugam spatiu de 25 si in dreapta ca sa nu se iveasca situatia de mai sus
- [x] renuntam la text-transform uppercase (nu reflecta designul)
- [x] reducem distanta dintre titlu si data cu 5px
- [x] line height pe title de 20px

sa iasa asa (ca aranjament nu ca aspect ratio):

![image](https://cloud.githubusercontent.com/assets/113568/19174572/55d449f8-8c38-11e6-85c1-c018a1259685.png)

**Comment by c0sm1n87** [comment]
adaugam si un text-shadow subtil negru ( cum am adaugat pe captionul headerului ) in caz ca imaginea are culoare predominanta alba?

**Comment by ngabyn** [comment]
Dap sounds good

**Comment by cristianraiber** [comment]
@c0sm1n87 - asta nu-i gata. Spacing-ul intre titlu' si data nu e ca in poza data de @ngabyn 
![post-banner-8x](https://cloud.githubusercontent.com/assets/7841556/19185656/4d19b82c-8c8b-11e6-9c2b-146c925ac1d2.png)

**Comment by c0sm1n87** [comment]
mda, my bad .. am citit micsorat la 5px in loc de cu 5px
