### ISSUE TITLE
Add support for <!-- more --> tag as post split

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#119]
![image](https://cloud.githubusercontent.com/assets/113568/19174701/8c544c5c-8c39-11e6-9e3c-cfcf41ad3997.png)

**Comment by c0sm1n87** [comment]
excerptul e delimitat de read more tag, deci asta merge fara sa mai facem nimic altceva. singura problema e ca nu apare "Read More". Read more button apare daca folosesti the_content(), dar se cam bate cap in cap cu tot ce am facut noi pana acum

**Comment by cristianraiber** [comment]
@ngabyn - o parere aici?

**Comment by ngabyn** [comment]
Trebuie sa incercam asta 👍 

global $more;
$more = false; 
the_content('');	
$more = true;

O sa testam zilele urmatoare
