### ISSUE TITLE
Debate: Search site wide or blog depending on navigation

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#120]
O chestie pe care am facut-o in trecut... 
* cand eram pe o pagina oarecare si cautam folosind formularul din header imi cauta site wide
* cand eram pe blog si completam field-ul de cautare imi returna rezultate doar din blog posts

* aici am putea sa aducem si o optiune gen .. "Bibistrocel not found, want to search on the entire website?"  in ideea de a schimba o cautare din blog in site wide... astept opinii :)

**Comment by cristianraiber** [comment]
@ngabyn - mi se pare un feature care n-ar trebui implementat by default, ci by user option. Schimba complet conceptul de search cu care ei sunt deja familiari

**Comment by ngabyn** [comment]
@cristianraiber putem sa concepem un mod de interpretare cat sa fie util userului
