### ISSUE TITLE
Add support for sticky posts (using default css classes)

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#122]

**Comment by cristianraiber** [comment]
@c0sm1n87 - daca adaugam support pt. sticky posts, trebuie adaugat si in style.css tag-ul `sticky-post`. Temele care suporta aceasta functionalitate, trebuiesc tag-uite in mod special.

**Comment by c0sm1n87** [comment]
https://github.com/MachoThemes/newsmag-lite/issues/127 am facut aici dupa designul cristinei, o sa adaug in style.css acum sticky-post tag ... mutam la celalt milestone?
