### ISSUE TITLE
Improved support for password protected posts

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#123]
![image](https://cloud.githubusercontent.com/assets/113568/19174886/ce6afe0a-8c3a-11e6-961f-6ca978f299c5.png)

Arata uratel acum, trebuie sa facem un mod uniform de a prezenta formularele la nivel de site

**Comment by c0sm1n87** [comment]
un design per formulare please

**Comment by ngabyn** [comment]
butonul de submit aici o sa respecte stilul de butoane rosii din styleguide

**Comment by ngabyn** [comment]
Am picat deacord cu cristina pe un stil, o sa il folosim pe acesta si la submit comment si la submit password

![image](https://cloud.githubusercontent.com/assets/113568/19557563/0771fa48-96cf-11e6-8c1e-4bbfa12f1728.png)


![image](https://cloud.githubusercontent.com/assets/113568/19557589/299faad4-96cf-11e6-8589-c8a671c537b2.png)

**Comment by ngabyn** [comment]
Pentru orice buton de submit ar trebui sa se respecte acelasi stil in principiu

**Comment by ngabyn** [comment]
- [x] Password protected form looks good,
- [ ] form submit should be consistent also
- [ ] custom forms should also be targeted here

**Comment by ngabyn** [comment]
![image](https://cloud.githubusercontent.com/assets/113568/19559138/080e377a-96d7-11e6-9a4c-2b68d5fc309b.png)

**Comment by ngabyn** [comment]
![image](https://cloud.githubusercontent.com/assets/113568/19593075/69c550c4-9787-11e6-9542-53f72eb7c3d8.png)

Clicked state doesn't work

**Comment by c0sm1n87** [comment]
hmm, vad in imaginea ta ca butonul e putin mai mare decat inputul, will look into it

**Comment by ngabyn** [comment]
In html asa pare ca nu au dimensiunile aceleasi

**Comment by c0sm1n87** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/10389279/19595776/396e5ca6-9794-11e6-8ed8-2d8caf0f1320.jpg)

**Comment by ngabyn** [comment]
Looks good now 👍 

![image](https://cloud.githubusercontent.com/assets/113568/19596530/cdd335d0-9797-11e6-9a3c-125532364fd4.png)

Dar starea de active (clicked) nu merge

**Comment by c0sm1n87** [comment]
https://github.com/MachoThemes/newsmag-lite/commit/4894b972085c75f126e947aaa3f93d9243d022db

am dat referinta aiurea in commit
