### ISSUE TITLE
Add support for Pingbacks and Trackbacks

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#124]
Clearly needs more styling .. urmeaza Cristina :)
![image](https://cloud.githubusercontent.com/assets/113568/19174920/1808a486-8c3b-11e6-84b4-611163487d7d.png)

**Comment by ngabyn** [comment]
![image](https://cloud.githubusercontent.com/assets/113568/19556571/6e97d490-96ca-11e6-908d-004c9f859941.png)

Se gaseste in styleguide

**Comment by c0sm1n87** [comment]
m`am chinuit toata dimineata sa testez treaba asta si mi`am dat seama pe urma ca eu sunt pe local. o putem lasa pe urmatorul milestone?

**Comment by cristianraiber** [comment]
@ngabyn, @c0sm1n87 - mutat pe 2.2.0

**Comment by c0sm1n87** [comment]
Implemented
