### ISSUE TITLE
Add support for post formats

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#125]

**Comment by cristianraiber** [comment]
@ngabyn - nu stiu daca asta-i neaparat o idee buna. Post formats au fost retrase din Core si urmeaza a fi excluse complet

**Comment by ngabyn** [comment]
@cristianraiber  Well if is still a core feature maybe we should support it as long as it works.

**Comment by ngabyn** [comment]
Butoanele naibii...
