### ISSUE TITLE
Social icons & search icon vertical alignment issue

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#128]
Nu's aliniate vertical iconitzele astea

----

![pasted_image_at_2016_10_07_15_22_1024](https://cloud.githubusercontent.com/assets/7841556/19190075/0ff71f2a-8ca4-11e6-83bc-017297c8c70f.png)

**Comment by c0sm1n87** [comment]
nu pot vedea poza
