### ISSUE TITLE
If Search is off the menu container should be md-12

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#132]

**Comment by c0sm1n87** [comment]
pai si cu social icons ce mai facem? nu mi se pare ok sa ascundem social menu doar ca el nu vrea search :)

**Comment by cristianraiber** [comment]
@ngabyn - aici ar trebui sa facem o noua bara, deasupra header area (cum e cea de news ticker in versiunea PRO) si sa le punem acolo, in dreapta. M-am mai jucat cu tema in week-end si mai mult de 4 item-uri in meniu, nu poti pune in acel span 6 :)

**Comment by ngabyn** [comment]
yup, inchidem asta si revenim cu un update pe structura in header
