### ISSUE TITLE
Split "Newsmag - hompage builder" in 4 widgets

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#136]
To be able to improve this one by one we have to split them and after that we can add some Epsilon controls on them

- [x] One column > Newsmag - Posts column
- [x] Two columns > Newsmag - Posts list vertical
- [x] Banner > Newsmag - Posts grid
- [x] Thumbnails > Newsmag - Posts list horizontal

**Comment by c0sm1n87** [comment]
si cu recent posts layout ce facem?

**Comment by ngabyn** [comment]
Recent prosts e un widget independent deja pt newsmag nu ?

**Comment by c0sm1n87** [comment]
ala e popular posts, builderu are 5 layouturi distincte

**Comment by ngabyn** [comment]
putem sa il facem si pe ala independent

**Comment by c0sm1n87** [comment]
am si eu nevoie de descrieri pentru widgets

**Comment by cristianraiber** [comment]
@c0sm1n87 

- *Newsmag - Posts Colum* - _Layout consits of a featured thumbnail, followed by a handful of posts that are smaller in size. Perfect for emphasising important news. _
