### ISSUE TITLE
Create image size for homepage slider

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#138]
Apar tot felul de probleme de aliniament din cauza dimensiunii, hai sa folosim un singur image size in asa fel incat sa fie uniform...   dimensiunea ar trebui sa fie  9999x600

**Comment by c0sm1n87** [comment]
are deja image size, nu cred ca asta ar fi o rezolvare ( sa maresc widthu la 9999 ). poate mai bine am folosi background image pe div decat actual img

**Comment by ngabyn** [comment]
O lasam pe mai tarziu, poate incercam imaginea ca background si umblam la background strech

**Comment by cristianraiber** [comment]
@c0sm1n87 - daca punem bg. image, nu mai poti link-ui imaginea catre postare and that's bad as well
