### ISSUE TITLE
Add preloader

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#144]
@ngabyn - ce parere ai de-un preloader ?

**Comment by c0sm1n87** [comment]
nici un site respectabil nu are preloader 👍

**Comment by ngabyn** [comment]
As spune sa ii tragem un epsilon toggle in general options

**Comment by cristianraiber** [comment]
Daca am implementat lazyLoading pe toate pozele, nu prea mai are sens un preloader.
