### ISSUE TITLE
Home header slider improvement

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#145]
![image](https://cloud.githubusercontent.com/assets/113568/19302482/fc33638c-906c-11e6-92cc-ae1e133dbe75.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - o mentiune aici - sagetile slider-ului apar doar cand faci hover pe slider, in rest, sunt cu opacitate 0 :) Doar pe mobile sa apara by default

**Comment by ngabyn** [comment]
![image](https://cloud.githubusercontent.com/assets/113568/19309436/6fbbc0d6-908d-11e6-983a-6001012c7453.png)

Where's your ruler dude ?

**Comment by cristianraiber** [comment]
Closing this as @ngabyn is working on it here: https://github.com/MachoThemes/newsmag-lite/tree/ProSlider
