### ISSUE TITLE
Improved sections aspect

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#148]
- [x] schimbam titlurile in widgeturile de homepage sub forma:
![image](https://cloud.githubusercontent.com/assets/113568/19346697/7072fe66-914d-11e6-84b9-376b5cef1ab6.png)

- [x] categoriile isi schimba si ele aspectul

Ps. In design se gaseste **newsmag_pro1A.psd**

**Comment by cristianraiber** [comment]
@c0sm1n87 - different font weights

---

![Uploading Screen Shot 2016-10-14 at 13.58.59.png…]()
