### ISSUE TITLE
Use IcoMoon app to load only font-awesome icons that are being used

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#152]
Acum incarcam toate iconitele font-awesome cand folosim doar 10-15 din ele ... n-are sens

**Comment by c0sm1n87** [comment]
hai sa ne decidem ce iconite folosim, facem pachetu si`l integram ( sa ne gandim si pe viitor ce om putea folosi ) :)

**Comment by cristianraiber** [comment]
@ngabyn - a little help here please? :D
