### ISSUE TITLE
Tag Archives: wrong title

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#160]
http://www.newsmag.machothemes.com/tag/clouds/

Should say: tags

**Comment by cristianraiber** [comment]
Aici e si vina mea ca n-am explicat mai bine de atat ... in loc de "archives" ar fi trebuit sa scrie: "tags archive: {tag_name}". Versiunea curenta, nu-i ok.

![image](https://cloud.githubusercontent.com/assets/7841556/19436884/60ceb618-947b-11e6-8f9a-af4c1731a3ad.png)

**Comment by c0sm1n87** [comment]
![capture](https://cloud.githubusercontent.com/assets/10389279/19467235/c098b7a4-9518-11e6-838b-b6be1d076a5e.PNG)
