### ISSUE TITLE
Category link missing from post meta on single posts 

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/newsmag-lite#162]
Ma refer atat la homepage cat si la pagina de single blog, nu am link direct catre categorie decat daca este pus un widget cu categorii sau daca exista linkuri cate categorii in meniu

**Comment by cristianraiber** [comment]
@c0sm1n87 - am putea afisa categoria din care face postarea langa data. Vezi screenshot.

![image](https://cloud.githubusercontent.com/assets/7841556/20134581/98ea239c-a674-11e6-8952-0efc8344e71b.png)
