### ISSUE TITLE
Widget titles should actually be links to the category 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#165]

**Comment by c0sm1n87** [comment]
https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/posts_column/layouts/posts_column_featured.php#L20
https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/posts_column/layouts/posts_column.php#L14
https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/posts_grid/layouts/posts_grid.php#L11
https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/posts_list_horizontal/layouts/posts_list_horizontal.php#L11
https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/posts_list_vertical/layouts/posts_list_vertical.php#L10

i don't get it :|

**Comment by cristianraiber** [comment]
Si cand e pus custom title? :)
