### ISSUE TITLE
Typography controls 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#167]
Exista deja un set de controale pt. Customizer in Riba PRO - made by me 💃 

@ngabyn - ce zici, il punem pe milestone-ul asta?

**Comment by ngabyn** [comment]
we can ...  o sa abordam ce am desenat eu cu ce ai facut tu...

**Comment by cristianraiber** [comment]
@c0sm1n87 - aici vreau sa implementam un control minimal in versiunea LITE. 2 font families din care pot alege, doar pt. content headings si pt. content paragraphs. Una dintre familiile existente din select, sa fie cea folosita momentan (nu mai stiu daca era Poppins sau se numea altfel). 

Adaugam upsell in panoul de typopgraphy: "For more font controls check-out the PRO version of Newsmag".
