### ISSUE TITLE
Fix vertical alignment on category tag

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#168]
![image](https://cloud.githubusercontent.com/assets/113568/19405408/cbfa5e90-927f-11e6-872d-d5a270c71880.png)

**Comment by cristianraiber** [comment]
![image](https://cloud.githubusercontent.com/assets/7841556/19436762/bba38d4e-947a-11e6-9271-57860651220b.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - nu e implementat asta

**Comment by c0sm1n87** [comment]
@cristianraiber am vbit ieri despre asta
