### ISSUE TITLE
Newsmag - Homepage Slider - Customisation options

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#170]
- [ ] "Today’s hot topics" to be editable
- [ ] the tag above to be visible or not via  epsilon toggle control - @cristianraiber opinion ?
- [ ] post author mentioned or not via epsilon toggle control - @cristianraiber opinion ?
- [ ] pager visible on desktop version or not via epsilon toggle control - @cristianraiber opinion ?

![image](https://cloud.githubusercontent.com/assets/113568/19405546/37604ab8-9281-11e6-99ea-c074a1e7ceed.png)

**Comment by cristianraiber** [comment]
@ngabyn - le-as muta ca si optiuni in versiunea PRO pe toate :)

**Comment by ngabyn** [comment]
@cristianraiber asa si facem!

**Comment by cristianraiber** [comment]
@ngabyn - moved to https://github.com/MachoThemes/newsmag-pro/issues/14
