### ISSUE TITLE
Meta: Date color different on home widgets 

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#171]
Design version:
![image](https://cloud.githubusercontent.com/assets/113568/19405588/ea7a4cfc-9281-11e6-96fa-d0915ec4a427.png)

Live version:
![image](https://cloud.githubusercontent.com/assets/113568/19405597/f78c960c-9281-11e6-8f6f-d9789f9ed4c1.png)

**Comment by cristianraiber** [comment]
Invalid, since: #172
