### ISSUE TITLE
Meta: Add comment icon on all homepage widgets

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#172]
We could follow the style below by Cristi :D  ... with red on hover
![image](https://cloud.githubusercontent.com/assets/113568/19405607/301c4602-9282-11e6-9d54-92096c5b770e.png)

**Comment by c0sm1n87** [comment]
modific si date`u ? ca aici vad ca e gri si icoana de "time", sau le fac ca acum pe ambele ( icoanele red, scris gri ) ?

**Comment by cristianraiber** [comment]
@c0sm1n87 - toate sunt gri; si icoanele si scrisul

**Comment by cristianraiber** [comment]
![image](https://cloud.githubusercontent.com/assets/7841556/19436730/978c22e0-947a-11e6-8c8e-c6b44b57fff5.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - still not working

**Comment by cristianraiber** [comment]
@ngabyn - sa afisam numarul de comentarii si pe post grid / post lists horizontal?

**Comment by ngabyn** [comment]
hai sa le punem si acolo ca sa fie uniform

**Comment by cristianraiber** [comment]
@c0sm1n87 

- [ ] adauga comentariile ca post meta pe widget: post grid, langa data

- [ ] adauga comentarii + data postarii sub titlul postarii pe widget: posts horizontal

- [ ] pe ambii widgetzi trebuie adaugat label-ul de categorie (cel cu fundal roshu')

**Comment by ngabyn** [comment]
👍 ar trebui duse si in PRO, arata ok aici!
