### ISSUE TITLE
Homepage - Posts column order

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#175]
The big image should be the sticky one from the category, and if it's not should be the latest one .

![image](https://cloud.githubusercontent.com/assets/113568/19405764/27248102-9284-11e6-9432-3250fb96a413.png)

**Comment by c0sm1n87** [comment]
By default, sticky posts merg pe main blog posts index - ca sa iau sticky posts per categorie (per scenariul asta), trebuie sa fac additional new WP_Query pentru fiecare widget in parte .. alta solutie nu prea vad :)

**Comment by ngabyn** [comment]
let's go with this pe one column

**Comment by cristianraiber** [comment]
@c0sm1n87 - ar putea fi folosita asta: `http://www.remicorson.com/modifying-the-current-query-with-pre_get_posts/`

**Comment by c0sm1n87** [comment]
test it first..

**Comment by cristianraiber** [comment]
@c0sm1n87 - am testat acum; am facut post-ul sticky, apare doar postarea featured, lipsesc cele de sub ea. 
![image](https://cloud.githubusercontent.com/assets/7841556/19437007/01ecf32a-947c-11e6-9f04-ac5a3e5d6ee2.png)

![image](https://cloud.githubusercontent.com/assets/7841556/19437013/0e1aae26-947c-11e6-8658-3a8af0175dc9.png)

**Comment by cristianraiber** [comment]
Pare sa mearga acum :)
