### ISSUE TITLE
Slider issue on 1366 x 768

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#176]
<img width="1440" alt="slider-bottom-issue" src="https://cloud.githubusercontent.com/assets/7841556/19407665/672c5978-92b1-11e6-889e-ecbd4245a48d.png">

**Comment by ngabyn** [comment]
Problema asta e doar din cauza ca una din imagini e mai mare si dimensiunea sliderului ramane aceeasi ... problema trebuie rezolvata din image size handling... o sa ma uit eu peste la un moment dat dar nu acum
