### ISSUE TITLE
Widget - Posts grid improvements

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#181]
@ngabyn commented on [Wed Oct 19 2016](https://github.com/MachoThemes/newsmag-pro/issues/21)

- [x] cand nu e nici un titlu da eroare
- [x] trebuie limitat la un numar de 8 items
- [x] label-ul de categorie, trebuia afisat deasupra titlului

![image](https://cloud.githubusercontent.com/assets/113568/19519148/493fe6cc-9613-11e6-9e0a-dacdd83a4c68.png)

![image](https://cloud.githubusercontent.com/assets/113568/19519034/b5ac418a-9612-11e6-8e62-8c118b59fa59.png)

**Comment by c0sm1n87** [comment]
nu pot sa replic elementul 3 din checklist

**Comment by cristianraiber** [comment]
Remaining issues moved in #184
