### ISSUE TITLE
Widget - Post list horizontal

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#182]
@ngabyn commented on [Wed Oct 19 2016](https://github.com/MachoThemes/newsmag-pro/issues/22)

Image size not loaded properly breaks layout

![image](https://cloud.githubusercontent.com/assets/113568/19519290/f6b6e882-9613-11e6-8447-e26088a37b11.png)

**Comment by c0sm1n87** [comment]
nu folosesti ultima versiune, ultima versiune are badgeul de categorie pe imagine

**Comment by ngabyn** [comment]
Asa se  pare, arata okay ca grid 👍 

- aici hai sa punem 12 elemente cu increment din 4 in 4 de data ce nu are rost sa vedem cate 6 elemente adica 4 pe prima linie si doar 2 pe cea dea doua

**Comment by ngabyn** [comment]
Titlul de categorie nu este centrat in dreptunghi, are 6px sus 8px jos

![image](https://cloud.githubusercontent.com/assets/113568/19520827/37c8c812-961a-11e6-9e84-6fd37df1c792.png)

**Comment by cristianraiber** [comment]
@ngabyn - eu i-am zis sa punem 6px sus ca pe Chrome, Mac era ok spatiat (masurat in PS). Se pare ca e un bug cross-browser cross-platform.

**Comment by ngabyn** [comment]
eu il vad in Firefox, o sa ma uit si peste chrome, ie sa vedem ce dumnezeu are ... poate gasim o solutie okay

**Comment by cristianraiber** [comment]
@ngabyn - l-am mutat pe urmator-ul milestone. It's non-blocking.
