### ISSUE TITLE
Widget - Posts list vertical

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#183]
@ngabyn commented on [Wed Oct 19 2016](https://github.com/MachoThemes/newsmag-pro/issues/23)

- [x] textul nu e centrat vertical
- [x] epsilon slider permite doar un numar de posts par, fa incremetul de 1

![image](https://cloud.githubusercontent.com/assets/113568/19519383/793a9772-9614-11e6-80aa-69463f877f4d.png)

**Comment by c0sm1n87** [comment]
epsilon slider permite doar par, pentru ca asa mi`ai zis sa`l fac acum 2 saptamani !! :-1:

**Comment by cristianraiber** [comment]
@c0sm1n87 - let me know if this is up for testing :)

**Comment by ngabyn** [comment]
👍
