### ISSUE TITLE
Widget - Posts grid improvements - part deux

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#184]
- [ ] cand am un element sticky imi ignora numerotarea
- [x] o sa schimbam aici incrementul in 2, sa putem sa setam doar 2,4,6,8

![image](https://cloud.githubusercontent.com/assets/113568/19519148/493fe6cc-9613-11e6-9e0a-dacdd83a4c68.png)

![image](https://cloud.githubusercontent.com/assets/113568/19519034/b5ac418a-9612-11e6-8e62-8c118b59fa59.png)

**Comment by ngabyn** [comment]
@c0sm1n87 daca nu poti reproduce il putem inchide e ok.
