### ISSUE TITLE
All homepage widgets improvement 

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#185]
- [ ] image size implemented
- [x] hai sa folosim elementul `<img>` in loc de imaginile puse ca background. Posts grid, spre exemplu, foloseste imaginea ca background.
- [x] la categorii, cand faci hover pe label-ul ala roshu', sa fie #000
- [x] Post column widget title still has diferent font weight than the rest of the homepage widgets
- [x] widget - posts column - schimbam titlul "Show date" in "Show date and comments" si ascundem si comentariile la off
- [x] toate labelurile de categorie ar trebui sa duca spre categorie in sine nu spre post
- [x] widget posts grid item sa aiba link pe categorie
- [x] widget posts grid item - data sa fie si ea cu gri precum comentariul curent

**Comment by c0sm1n87** [comment]
image size e implementat din initial commit. problema nu e din cod - imaginea trebuie sa aiba totusi o dimensiune minima ca media uploaderul sa aiba ce decupa.

https://github.com/MachoThemes/newsmag-lite/blob/master/functions.php#L91-L94

https://github.com/MachoThemes/newsmag-lite/blob/master/template-parts/content.php#L15

https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/homepage_slider/layouts/slider.php#L17

https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/homepage_slider/layouts/slider.php#L17

https://github.com/MachoThemes/newsmag-lite/blob/master/inc/widgets/posts_column/layouts/posts_column_featured.php#L39

**Comment by ngabyn** [comment]
Aici avem o imagine de 560x300 si nu e deajuns:

![image](https://cloud.githubusercontent.com/assets/113568/19550594/d9c408d2-96b2-11e6-9229-8e914010ab05.png)

**Comment by ngabyn** [comment]
![image](https://cloud.githubusercontent.com/assets/113568/19550705/633a18a4-96b3-11e6-9787-93d846d3ba6f.png)

**Comment by c0sm1n87** [comment]
30f5563a574cbe5eff73405203d8d6f086120a06

**Comment by ngabyn** [comment]
Cred ca ar fi mai ok sa denumim optiunea "Show date" in "Show date and comments" si evident sa ascunda si comentariul ca arata uratzel doar cu iconitza de comentariu

![image](https://cloud.githubusercontent.com/assets/113568/19552315/fc912f52-96b7-11e6-8d2d-9850153d0c85.png)

**Comment by ngabyn** [comment]
![image](https://cloud.githubusercontent.com/assets/113568/19552480/8f6d335c-96b8-11e6-9133-a5c8852dfdec.png)

**Comment by ngabyn** [comment]
S-o intamplat ceva cu categoria pe post list

![image](https://cloud.githubusercontent.com/assets/113568/19554337/ccf3c81e-96c0-11e6-9600-9e24d5145ce9.png)

**Comment by ngabyn** [comment]
![image](https://cloud.githubusercontent.com/assets/113568/19555506/c16b4594-96c5-11e6-8f7d-3c4cc7e8574f.png)

Link-ul de categorie sa duca spre categoria post-ului nu spre el in sine.

**Comment by ngabyn** [comment]
Post grid item  nu are link deloc

![image](https://cloud.githubusercontent.com/assets/113568/19555554/f0cb8894-96c5-11e6-9662-ba6702e891dd.png)

**Comment by ngabyn** [comment]
Data ar fi ok sa fie si ea cu gri, pare okay :D 
![image](https://cloud.githubusercontent.com/assets/113568/19555629/520f16d4-96c6-11e6-849b-7c5458912f1d.png)

**Comment by c0sm1n87** [comment]
widget posts grid item - data sa fie si ea cu gri precum comentariul curent - pe placeholder se vede bine, dar pe o imagine deschisa la culoare nu se mai poate citi

**Comment by ngabyn** [comment]
@c0sm1n87 okay, atunci hai sa le facem albe pe amandoua
