### ISSUE TITLE
Widget slider - headline not editable

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#186]
![image](https://cloud.githubusercontent.com/assets/113568/19537189/b79db998-9657-11e6-9f03-1ab035711cc9.png)

**Comment by cristianraiber** [comment]
@ngabyn - field-ul title din widget n-ar fi trebuit redenumit, ca si in newsmag PRO ? https://github.com/MachoThemes/newsmag-pro/blob/master/inc/widgets/homepage_slider/class-widget-newsmag-homepage_slider.php#L69

**Comment by ngabyn** [comment]
@cristianraiber ideea e ca si cei din lite ar dori sa il modifice nu ?

**Comment by cristianraiber** [comment]
@ngabyn dap
