### ISSUE TITLE
Add edit link to all homepage content widgets when user logged in

### ISSUE THREAD

**Issue by ngabyn** [MachoThemes/newsmag-lite#190]
Am facut un preview mai jos:

![image](https://cloud.githubusercontent.com/assets/113568/19554454/4f977112-96c1-11e6-9e61-6848f980b885.png)

Am folosit  .fa-edit pt icon

**Comment by ngabyn** [comment]
👍

**Comment by ngabyn** [comment]
All links point to  widgets.php

![image](https://cloud.githubusercontent.com/assets/113568/19558941/c45bbe7c-96d5-11e6-9b99-0b5c5e71ab76.png)

**Comment by c0sm1n87** [comment]
am crezut ca trebuie sa linkuiasca catre pagina de widget. o sa linkuiasca catre post in urmatorul commit

**Comment by ngabyn** [comment]
sounds good!

**Comment by ngabyn** [comment]
👍
