### ISSUE TITLE
New layout for single blog posts

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#200]
Trebuie o abordare mai a la blog aici, in ideea in care avem featured image - content - author area - related posts - comment form.

**Comment by ngabyn** [comment]
Procedam in felul urmator:

Adaugam o optiune suplimentara in customizer > blog > single post  numita "Featured image in content" de tip Epsilon Toggle 

Featured image in content -  ON
Featured image in content -  OFF

**Comment by cristianraiber** [comment]
@c0sm1n87 

![image](https://cloud.githubusercontent.com/assets/7841556/19806179/c69f0cdc-9d21-11e6-9ddd-1b2954b6bd52.png)

**Comment by cristianraiber** [comment]
O problema cu spacing-ul/ marginile pozei fata de restul continutului

**Comment by cristianraiber** [comment]
@c0sm1n87 vezi: https://github.com/MachoThemes/newsmag-pro/issues/38

**Comment by cristianraiber** [comment]
@c0sm1n87 - asta trebuie testata?
