### ISSUE TITLE
About {theme_name} page step order

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#214]
Mi se pare putin peste mana faptul ca in primul tab cu "Getting Started" sunt toti cei trei pasi. Acesti pasi sunt: 

1. Recommend actions
2. Check documentation
3. Go to customizer

Primul pas ma va duce in al doilea tab "Recommended Actions". Pentru a vizualiza cel de-al doilea pas va trebui sa ma intorc in primul tab "Getting Started". 

Utopic, toti acesti 3 pasi ar trebui sa faca parte din mantra "getting started" - sa ma ajute sa incep lucrul cu tema. Din punctul meu de vedere, experienta este una fragmentata momentan.

Ma asteptam ca cei 3 pasi sa ma ajute sa-mi instalez si configurez tema. Pasul 2 ma scoate din tema, pasul 3 ma duce in Customizer.

**Comment by cristianraiber** [comment]
@c0sm1n87 - aici problema era in felul urmator:

pashii 1-3 nu prea sunt liniari dpdv ai scopului. E vorba de phrasing. Momentan, l-am scos de pe milestone. O sa ma mai gandesc cum poate fi abordata asta aici.
