### ISSUE TITLE
First 2 tabs, no context given

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#217]
Getting started, Step 1 si Recommended actions, nu imi explica exact care este scopul acestor actiuni. Nu se intelege din : 

---

![image](https://cloud.githubusercontent.com/assets/23457094/20278602/05f68574-aaae-11e6-8636-7dbfe0c8d7dd.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - aici trebuie adaugat un pic de context. Gen, sa mentionam ca indeplinirea acelor pasi este pentru a avea o tema setup-ata ca in demo.
