### ISSUE TITLE
Improve changelog interface

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#221]
- sa poti da click pe link-uri
- changelog-ul sa includa titlul tichetelor din Git

**Comment by c0sm1n87** [comment]
am pus linkuri catre milestones .. mi se pare overkill sa iau linkuri de la toate issues ( primul milestone avea 100~ de issues )

**Comment by cristianraiber** [comment]
@c0sm1n87 - o sa generez eu changelog-ul la un moment dat din git history; am facut ceva progrese pe partea asta, da' nu e inca gata :)
