### ISSUE TITLE
Site title - display uppercase

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#222]
Adauga un checkbox sa transforme titlul in majuscule ( by default sa fie enabled). 

--- 

### Back-end:
![image](https://cloud.githubusercontent.com/assets/23457094/20299312/1950d474-ab23-11e6-9e26-92ea3e92f7c2.png)

---

### Front-end:
![image](https://cloud.githubusercontent.com/assets/23457094/20299330/2dfd8336-ab23-11e6-8cf8-8c5492ee740f.png)

**Comment by c0sm1n87** [comment]
Nu e mai usor sa scoatem uppercase`ul si userul sa foloseasca caps lock daca vrea majuscule? :+1: :)

**Comment by cristianraiber** [comment]
@c0sm1n87 - da, e o abordare mai simpla si mai user friendly. Let's do that :)

**Comment by AnaMaican** [comment]
In customizer- widgets - Homepage - Content area, avem aceesi problema cu titlurile postarilor. Poti te rog sa scoti si de aici uppercase-ul?

**Comment by AnaMaican** [comment]
Customizing ▸ Widgets - Footer ...pls si de aici scos uppercase-ul din titluri.

**Comment by c0sm1n87** [comment]
in Homepage - Content area doar titlurile widgetzilor sunt uppercase .. asta cred ca vrea sa fie in concordanta cu celelalte badge`uri de categorie (daca nu este setat titlul manual, e luat numele categoriei).

PS: am scos de la footer uppercaseul

**Comment by AnaMaican** [comment]
Cel mai corect cred ca ar fi sa scoatem uppercase-ul si din titlurile widgetzilor din Homepage - Content area, ca sa nu fortam utilizatorul si sa ramana la latitudinea user-ului.
