### ISSUE TITLE
Cutomizer tablet/mobile testing issues

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#225]
Link-urile din meniul de navigatie nu functioneaza (tablet testing).
![image](https://cloud.githubusercontent.com/assets/23457094/20303580/bb585b14-ab34-11e6-9931-d2cbb04fe816.png)

---
Meniul de navigatie este colapsat peste slider (mobile testing).

![image](https://cloud.githubusercontent.com/assets/23457094/20303837/f74266b4-ab35-11e6-9a80-a006393f19d2.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - e vorba de testarea responsive din customizer. Se da click pe iconitele din partea dreapta jos a customizer-ului, cele de mobile/tablet si rezulta ce-i mai sus.

**Comment by c0sm1n87** [comment]
@cristianraiber stiu de butoanele alea 👍

**Comment by AnaMaican** [comment]
@c0sm1n87  inca se intampla ce am descris mai sus si pentru tableta si pentru mobil.

![image](https://cloud.githubusercontent.com/assets/23457094/20427789/5bd998d6-ad8e-11e6-9896-df59d2974fb9.png)

**Comment by c0sm1n87** [comment]
hmm, la mine nu se intampla .. o sa mai verific 

![snip](https://cloud.githubusercontent.com/assets/10389279/20427949/235aa4cc-ad8f-11e6-824e-77052d8a792c.JPG)

**Comment by c0sm1n87** [comment]
@AnaMaican sa testezi si acum, am scos icoana de search (ar trb sa fie mai mica "bara")

**Comment by AnaMaican** [comment]
![image](https://cloud.githubusercontent.com/assets/23457094/20571964/255d9776-b1b2-11e6-8a3d-4aa9c7ac3a1c.png)

@c0sm1n87 - aici pare sa fie o problema cu modul in care/cat se restrange slider-ul pe mobil

**Comment by c0sm1n87** [comment]
@AnaMaican modul in care se restrange sliderul pe mobil e dat de aspect ratio... la modul in care se genereaza acum sliderul .. nu pot decat sa distorsionez imaginea la un anumit height
