### ISSUE TITLE
Sticky nav logo issue

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#227]
Logo img. intra peste continutul meniului cand fac scroll.

![image](https://cloud.githubusercontent.com/assets/23457094/20310281/0126a410-ab54-11e6-8793-d99c26360a75.png)

**Comment by c0sm1n87** [comment]
Am facut ceva modificari la meniu pentru smaller devices, dar nu stiu daca putem evita scenariul asta in totalitate. Daca userul nu isi lasa loc pentru logo in menu bar, ce putem sa-i facem ? :P

Momentan am scos sticky functionality pentru rezolutii mai mici de 768px

**Comment by cristianraiber** [comment]
@c0sm1n87 - vezi ca aici mai e o problema. Logo-ul din sticky navbar capata niste dimensiuni complet diferite fata de cel din header si il lungeste. Pare ca si cum acolo fortezi un width: 100%
