### ISSUE TITLE
Customizer Typography Issues

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#233]
1. Cand modific in Headings -oricare din cele trei select-uri- nu se intampla nimic.
2. In Paragraph, nu se mai modifica fontul ca weight incepand cu valoarea 700. Nu se vede nici o diferenta pe front-end intre 700-900. Trebuie verificat daca familia de fonturi folosita, suporta ca weight toate valorile afisate. ( a fost mutat: https://github.com/MachoThemes/newsmag-lite/issues/235 ).
3. Scoate te rog din select-uri ' Select font' si 'Select font Style'. Nu au sens, deoarece Select font afiseaza font-ul Lato si Select font Style font-ul Normal.

**Comment by c0sm1n87** [comment]
1. l-am testat -- seems to work ok ( content headings sunt taguri de h1 h2 h3 h4 h5 h6 din blog posts )
2. Va fi implementata o solutie de genul in versiunile urmatoare. Nu e chiar cel mai simplu lucru de facut! :)
3. Select Font, Select font style, Select font weight sunt puse acolo pentru a-ti oferi un "default". The point is: e mult mai usor sa get back to default settings.

**Comment by AnaMaican** [comment]
1. Aaa eu testam heading-urile titlurilor articolelor din blog. Astea nu se modifica deloc?
3. Ok, am inteles. Atunci, cand intru prima data, field-urile nu ar trebui sa fie pre-populate cu valorile folosite in site? Selesct font style si select font nu ar trebui inlocuite cu theme default values?

**Comment by c0sm1n87** [comment]
1. Nu, typography controls din lite afecteaza doar elemente din continutul blog postului.
2. By default ( cand nu ai modificat nimic in fields ) controlul asta nu face nimic. In momentul cand o valoare este schimbata, se insereaza in pagina noul stil. Daca as pre-popula fieldurile cu theme default values, controlul o sa adauge stilurile tot timpul (stiluri care suprascriu default CSS degeaba). LITE version are 3 font families, dar PRO-ul are in jur de 20 ( cu posibilitatea sa adaugam toate Google Fonts ) - deja devine greu sa "gasesti" fontul default :)

Daca nu iti place labelul, il putem schimba in Theme Default 👍

**Comment by AnaMaican** [comment]
2. Da, pai atunci cel mai bine ar fi sa schimbam labelul in Theme Default, asta daca sunt de acord si @cristianraiber si @ngabyn . :)

**Comment by cristianraiber** [comment]
👍

**Comment by c0sm1n87** [comment]
am schimbat titlul

**Comment by cristianraiber** [comment]
@c0sm1n87 - legat de punctul 1 de aici: https://github.com/MachoThemes/newsmag-lite/issues/233#issuecomment-261190424 

Titlurile postarilor de blog nu sunt afectate de nici un control de typography?

**Comment by c0sm1n87** [comment]
possible duplicate #235
