### ISSUE TITLE
Customizer ▸ Widgets Footer 2 

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#234]
In partea de customizer - footer 2, in postarile recente, se poate scoate din ' Display post date?' semnul intrebarii, sau e default din wordpress?

![image](https://cloud.githubusercontent.com/assets/23457094/20389745/e6000a4c-acd3-11e6-90a6-40ae0577acc9.png)

**Comment by c0sm1n87** [comment]
este default WP

**Comment by cristianraiber** [comment]
Inchidem daca-i invalid.
