### ISSUE TITLE
Customizer typography improvements

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#235]
In Paragraph, nu se mai modifica fontul ca weight incepand cu valoarea 700. Nu se vede nici o diferenta pe front-end intre 700-900. Trebuie verificat daca familia de fonturi folosita, suporta ca weight toate valorile afisate.

**Comment by AnaMaican** [comment]
In Headings si in Paragraphs, fontul Lato nu functioneaza decat cu doua weight-uri, unul este de la 100-400 si cel de-al doilea de la 700-900. 
Heading-urile se modifica in cadrul postarii din blog de exemplu 'titlu 1': 

![image](https://cloud.githubusercontent.com/assets/23457094/20496507/1dc59cc8-b02e-11e6-802f-77169167cf26.png)

dar nu se modifica si titlul postarii din blog index, de exemplu 'Test Ana #1':

![image](https://cloud.githubusercontent.com/assets/23457094/20496677/d0ad09de-b02e-11e6-9cbf-04eb4336e540.png)

**Comment by c0sm1n87** [comment]
am rezolvat treaba cu Lato font-family, dar cu titlul articolului nu am facut nici o modificare (practic el nu face parte din "continut" )

**Comment by cristianraiber** [comment]
pai inseamna ca nici in pro nici in lite, nu se pot schimba titlurile articolelor .. Nu e ideal :)

**Comment by c0sm1n87** [comment]
cu toate ca cea mai simpla solutie ar fi sa adaug si titlul in "scope" nu cred ca e si cea mai buna .. o sa o adaug pentru 2.1.6 si vedem feedback
