### ISSUE TITLE
Customizer- sticky menu- logo issue

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#236]
Am sticky navbar activat si pe tableta si telefon se intampla urmatoarele lucruri: 

![image](https://cloud.githubusercontent.com/assets/23457094/20429757/3f7fd550-ad99-11e6-8706-6d18690ee30e.png)

![image](https://cloud.githubusercontent.com/assets/23457094/20429777/6cae718a-ad99-11e6-8113-ecdaaca3030e.png)

Intra logo-ul peste meniu si se deplaseaza iconitele la dreapta.

**Comment by c0sm1n87** [comment]
sticky functionality nu ar trb sa faca nimic daca rezolutia ecranului este mai mica de 768px, ce browser folosesti?

**Comment by cristianraiber** [comment]
@c0sm1n87 Chrome foloseste :)

**Comment by c0sm1n87** [comment]
sa iei ultima versiune ( nu ar mai trb sa apara logoul acolo )

**Comment by cristianraiber** [comment]
@c0sm1n87 - de ce ai scos sticky navbar < 768px? vreau sa-mi dau seama de logica :) 
@ngabyn - pareri ?

**Comment by c0sm1n87** [comment]
@cristianraiber pe actual phone .. navbarul ocupa ff mult din screen ( ma gandesc ca ar trebui sa gandim o solutie de mobile menu gen fullscreen or smth ) si nici nu poti sa vezi toate iteme daca ai un numar mare ( basically, acopera tot screenul si cand scrolluiesti .. bara ramane lipita de top edge ). basically, not usable

**Comment by ngabyn** [comment]
Cred ca ar fi ok sa scoatem search-ul de acolo momentan nu de alta da' e prea mult pe ui

**Comment by cristianraiber** [comment]
@ngabyn - deci tu zici sa pastram sticky dar sa scoatem search-ul, right?

**Comment by ngabyn** [comment]
dap

**Comment by cristianraiber** [comment]
@c0sm1n87 ce-a zis @ngabyn suna ok, let's try that ... pe mobil intr-adevar ocupa cam mult spatiu da' e util acel sticky pt. a avea acces rapid la nav ...

**Comment by c0sm1n87** [comment]
@cristianraiber problema e in felul urmator. daca ai un element care e "ancorat" de top edge nu poti sa scrolluiesti in interiorul sau ( nu poti vedea toate menu items, decat ce intra in viewport )

**Comment by cristianraiber** [comment]
@c0sm1n87 - sticky nu mai functioneaza nici pe tableta nici pe mobile ... e intentionat comportamentul asta?

**Comment by c0sm1n87** [comment]
sticky nu functioneaza pe "mobile" menu ( care e toggle ), tabletele cu viewportul mai mare de 768 ar trb sa vada meniul normal si sa mearga stickyiul
