### ISSUE TITLE
Customizer- typography- Line Height issue

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#237]
Daca treci de 99 de pixeli se intampla asta:

![image](https://cloud.githubusercontent.com/assets/23457094/20497169/d71d1b86-b030-11e6-8628-1b4ac1791fe6.png)

**Comment by AnaMaican** [comment]
Nu ar trebui implementat si in zona asta ceva default? 

![image](https://cloud.githubusercontent.com/assets/23457094/20497575/5b7091fa-b032-11e6-845b-c3d352664f4a.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - poate-ar fi o idee buna sa re-introducem acele controale de default, pe care le-am amanat?

**Comment by AnaMaican** [comment]
Putem sa mai adaugam un control de default si pentru Pargraphs separat? Acum daca vreau sa resetez paragraph-ul imi reseteaza si Font Size si Line Height fiind pe acelasi control.

![image](https://cloud.githubusercontent.com/assets/23457094/20596399/fd013f54-b246-11e6-85ca-d142772b865b.png)

**Comment by c0sm1n87** [comment]
@AnaMaican - reset to default este per control, nu per individual field. ar insemna sa pun 5 butoane de default intr`un singur control .. pe langa ca ar arata urat, ar fi si confusing rau

**Comment by cristianraiber** [comment]
@c0sm1n87 - confusing ... n-ar fi. Asa au facut si cei de la Divi: https://cdn.elegantthemes.com/gallery/divi/images/customizer-header.gif

**Comment by AnaMaican** [comment]
La Headings este pe tot field-ul, nu pe fiecare control in parte. Nu merge si la Paragraphs separat de Font Size si Line Height?

![image](https://cloud.githubusercontent.com/assets/23457094/20658984/5c67e452-b549-11e6-944a-f5c35f94f0c8.png)

**Comment by cristianraiber** [comment]
@AnaMaican - de fapt, headings nu au si celelalte optiuni de line height si font-size :) Optiunea de reset to default este valabila pt. tot grupul de optiuni pe care-l vezi acolo.

**Comment by AnaMaican** [comment]
ok :) atunci facem cum doreste @cristianraiber.
