### ISSUE TITLE
Widget - New footer - Categories and Archives select issue

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#241]
Casutele select-urilor de Archives si Categories au borderele rotunjite in partea stanga si difera si constructia cuvantului.

![image](https://cloud.githubusercontent.com/assets/23457094/20628846/296e94b6-b331-11e6-80f3-09b4909c9b97.png)
![image](https://cloud.githubusercontent.com/assets/23457094/20628853/335cd92e-b331-11e6-8f25-8ade5f797880.png)
---

PSD: 

![image](https://cloud.githubusercontent.com/assets/23457094/20628950/b7a2da80-b331-11e6-8ead-2699bc24f8a8.png)
![image](https://cloud.githubusercontent.com/assets/23457094/20628979/d76c40a4-b331-11e6-8552-b0ecc906df32.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - "constructia cuvantului" se refera la faptul ca in PSD aveau niste sageti inaintea lor acele placeholdere "- placeholder -" vs "placeholder"

**Comment by AnaMaican** [comment]
"constructia cuvantului" se refera la faptul ca in PSD aveau niste sageti inaintea lor acele placeholdere "- placeholder -" vs "placeholder"

**Comment by c0sm1n87** [comment]
@AnaMaican - optiunile selectului sunt date de catre wordpress direct ( eu nu le modific in nici un fel ). O sa ma uit sa vad daca pot face border-radiusul acela pe dreapta ( daca nu, o sa trb sa indrept si pe stanga )

**Comment by cristianraiber** [comment]
@c0sm1n87 - trebuie facute drepte peste tot :D

**Comment by AnaMaican** [comment]
@cristianraiber sa ii dai te rog fix-ul lui Cosmin.
