### ISSUE TITLE
Widget - New footer - Categories and Archives select issue 

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#242]
Cand dau click pe sageti nu se deschis select-urile. Functioneaza cu click oriunde in casuta, mai putin pe sageti.

![image](https://cloud.githubusercontent.com/assets/23457094/20633026/d01379ee-b34a-11e6-8c18-29bcb0de23db.png)

**Comment by cristianraiber** [comment]
@c0sm1n87 - asta de mai jos se intampla dupa ce s-a deschis select-ul si am dat click in afara lui. Also, scoate si outline-ul pls :) 

![image](https://cloud.githubusercontent.com/assets/7841556/20669310/320500e0-b57c-11e6-8295-cb7fb659a623.png)

**Comment by c0sm1n87** [comment]
nici in chrome, nici in firefox nu mi se intampla treaba asta .. ala pare ceva browser specific .. daca`mi poti zice exact ce e ( inset shadow? )

**Comment by cristianraiber** [comment]
@c0sm1n87 - la mine pe mac, in Chrome se intampla asta de mai sus
