### ISSUE TITLE
Blog - Single Post - Breadcrumbs issue customizer

### ISSUE THREAD

**Issue by AnaMaican** [MachoThemes/newsmag-lite#247]
Nu incape/apare toata informatia pentru Breadcrumbs.

![image](https://cloud.githubusercontent.com/assets/23457094/20669923/5760ef5e-b57f-11e6-8c63-002b119f6036.png)

**Comment by c0sm1n87** [comment]
fa`mi te rog un screen la tot ecranul

**Comment by cristianraiber** [comment]
@c0sm1n87 - pai iti face degeaba la tot ecranul. Pe rezolutia ei, toggle-ul de breadcrumbs este f jos / f aproape de iconitele pentru responsive. Ar trebui marit z-index-ul la pop-up-ul cu explicatia.

**Comment by c0sm1n87** [comment]
tot sistemul asta cu tooltip e faulty.. ma gandesc ca ar fi mult mai ok sa le mutam undeva in dreapta .. ex:

![untitled-1](https://cloud.githubusercontent.com/assets/10389279/20710801/d43719de-b644-11e6-9734-b18e86475669.jpg)

**Comment by cristianraiber** [comment]
@c0sm1n87 - tool-tip-ul isi pastreaza pozitia, doar explicatia sa apara din dreapta?

**Comment by cristianraiber** [comment]
@c0sm1n87 - nu prea e ok solutia asta, se urca peste content-ul temei la viewport-uri mai mici :)

**Comment by ngabyn** [comment]
@c0sm1n87 @cristianraiber in contextul de mai sus tooltip-ul ar trebui sa se afiseze deasupra nu dedesubt lucru care ar rezolva problema.

**Comment by cristianraiber** [comment]
O solutie ar fi, atunci, ca toate tooltip-urile sa le mutam deasupra question mark-ului si nu dedesubt. @c0sm1n87 - what do you say?

**Comment by c0sm1n87** [comment]
cred ca ar rezolva problema asta 👍

**Comment by cristianraiber** [comment]
@c0sm1n87 - hai sa marim aici z-index-ul pt. pop-up-urile astea ca sa se poata "urca" peste zona din customizer din partea de sus ... problema e 90% rezolvata, ar mai ramane doar scenariul in care faci hover peste o optiune aflata f. aproape de partea de "header" a customizer-ului.
