### ISSUE TITLE
Menu height issue; multiple menu items 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#256]
Not scrolling:

![image](https://cloud.githubusercontent.com/assets/7841556/21318085/737a8578-c610-11e6-89e6-846f38302e31.png)

---

Scrolling & sticky:

![image](https://cloud.githubusercontent.com/assets/7841556/21318097/8257bbba-c610-11e6-88d9-7c3dd704f7bc.png)

---

Before the 1.16 update, the menu could hold all those menu items by expanding (in height).

**Comment by cristianraiber** [comment]
Client URL: http://www.greatwonders.top/
HelpScout ticket: https://secure.helpscout.net/conversation/294288404/3608/?folderId=598337

**Comment by c0sm1n87** [comment]
I removed height from menu in a previous update 73a79176f0de94f2697557742e1a3c7e9acfb2b3
