### ISSUE TITLE
Social menu header issue

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/newsmag-lite#260]
Utilizatorii isi doresc sa poata folosi si un meniu normal in zona de header. Problema este ca orice meniu ar incerca sa plaseze in zona respectiva, care nu contine link-uri catre site-uri de social media, nu functioneaza corespunzator.

**Comment by c0sm1n87** [comment]
closed by mistake

**Comment by cristianraiber** [comment]
This shouldn't be an issue, as that's how the social menu works.
