### ISSUE TITLE
Replace comma with slash in breadcrumbs

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/newsmag-lite#263]
To replace the comma between a post's categories in breadcrumbs with a slash. 
![e45c0f98c68be29178e51e5b2dc37d0e](https://cloud.githubusercontent.com/assets/26008574/24144507/1fa013d2-0e36-11e7-9a1e-5583f22282d8.png)

**Comment by c0sm1n87** [comment]
'/' is an ancestral separator, while the comma separates the "categories" - which are all on the same level
