### ISSUE TITLE
Post excerpt lenght does not work

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/newsmag-lite#278]
![2a880a63fa17e4205af858505b2e8bfd](https://user-images.githubusercontent.com/26008574/36421560-98f2be24-1641-11e8-8e41-f4ef89ac2341.png)
You cannot add a different excerpt length. You can move the slider but it does not save it.

**Comment by ngabyn** [comment]
* found it, runs on older version of epsilon, have a fix, need assistance, @giucu91
