### ISSUE TITLE
 social icons not showing in the footer widget

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/newsmag-lite#281]
https://wordpress.org/support/topic/follow-social-icon-button-not-showing-in-footer-widget/

**Comment by skfaisal93** [comment]
What is the status of this issue?

**Comment by cristianraiber** [comment]
@skfaisal93 - it has the status of open.

**Comment by skfaisal93** [comment]
What is the progress on this bug?

@mplusb please look into this.
