### ISSUE TITLE
Change theme color

### ISSUE THREAD

**Issue by skfaisal93** [MachoThemes/newsmag-lite#282]
Add an option in theme customize setting to change theme color.

**Comment by giucu91** [comment]
Hello @skfaisal93 ,

In the lite version of NewsMag you can change only the header text color and the body background color. If you want more control take a look at the PRO version : [https://www.machothemes.com/theme/newsmag-pro/](https://www.machothemes.com/theme/newsmag-pro/)

I'll close this ticket.

**Comment by skfaisal93** [comment]
ok. close it.
